# Assessment
\label{sec:assessment}

This course uses five methods of assessment, each designed with the incoming student with no background in statistics or computing in mind. 
First, we have weekly computing labs which are completed in groups. With these labs, students without any coding background can benefit from the prior coding experience of other students in the group. 
However, in an effort to make sure that each student, including those with no computing experience, has weekly practice in coding we also assign individual homework assignments as well. 
Finally, because programming plays a central role in the course, we incorporate coding exercises into the midterm exams. 
In order to accommodate first-time programmers in which a timed coding exam may prove to be infeasible, the midterms are set as take-home exams and the students are allowed to use books, notes, and the internet to complete them.

Participation also factors into the final grade of students in the course. In addition, voluntary participation such as answering a question or being called on to answer a question has been shown to cause higher anxiety in large introductory courses than working in groups on in-class exercises [@england2017student]. Therefore, instead of relying solely on a potentially subjective measure of voluntary participation, participation scores of students in this class are made up of a check / no check type grade on their team-based in-class application exercises (they get a check if they were in class for the day) as well as their engagement on the online course discussion. 

Many of the assignments and assessments in the course are designed to prepare students for the final project, which, in a nutshell, asks students to "Pick a dataset, any dataset, and do something with it." The actual assignment, of course, goes into a lot more details than this, but ultimately students are asked to work in teams to pick a new (to them) dataset and an accompanying research question and answer the question using methods and tools they learned in the course. We specifically ask them to not feel pressured to apply everything they learned, but to be selective about which method(s) they use. They are also encouraged to try methods, models, and approaches that go beyond what they learned in the course and additional support for implementing these is provided during office hours.

There are three main reasons for assigning this team-based final project. First, in a class where students start off with no prerequisite knowledge, it is hugely rewarding for them to see that they can go from zero to full fledged collaborative and reproducible data analysis within the span of a semester, and hopefully this leaves them wanting to learn more. Second, for the most part, teamwork results in a better final product than students would accomplish individually. And lastly, teams are more adventurous than individual students, and are more likely to venture outside of what they learned in the class and learn new tools and methods to complete their projects. 

Teams turn in a project proposal roughly one-month before the final project is due with their data and proposed analysis. These proposals are reviewed carefully and feedback is provided to the students. Teams can choose to revise their proposals based on the feedback, and thereby increase their score on the proposal stage of the project. The final deliverables of the project are a 10-minute presentation during the scheduled final exam time and a write-up that goes into further depth than the presentation can in the allotted time. The final write-up is an R Markdown file, but unlike the earlier assignments, code chunks are turned off so that only the prose and the output/plots are visible to the reader. This encourages students to pay attention to wording, grammar, and most importantly flow since their narrative isn't interrupted with large chunks of code.